In [29]:
import os
import ctgomartini as ct
from ctgomartini.api import MartiniTopology
from function import *
import subprocess

In [30]:
working_dir = "/home/ys/CommonUse/Martini/CTGoMartini/tests/data/UmbrellaSampling/GlnBP/"
os.chdir(working_dir)

In [31]:
def Distance(p1,p2):
    return np.linalg.norm(p1-p2)

def Cal_Dist_from_atoms(atom1, atom2):
    p1=atom1.position/10
    p2=atom2.position/10
    r=Distance(p1,p2)
    return r

u = mda.Universe('minimized.gro')
Cal_Dist_from_atoms(u.atoms[130-1], u.atoms[289-1])

FileNotFoundError: [Errno 2] No such file or directory: 'minimized.gro'

In [ ]:
def Compare_OMM_GMX(working_dir, epsilon_r=15.0):
    print(working_dir)
    os.chdir(os.path.join(working_dir, "openmm"))
    strfile = "md.gro"
    topfile = "system.top"

    simulation = OMM_setSimulation(strfile, topfile, epsilon_r=epsilon_r, temperature=310.15, double_precision=True)
    OMM_calStrfile(strfile, simulation, set_vsite=True)

    omm_energy=Load_energy(clean=True)
    omm_forces=Load_forces(clean=True)
    print(omm_energy)
    # gmx
    os.chdir(os.path.join(working_dir, "gmx"))

    # GMX_set(CreateMDP=False, double_precision=True)
    GMX_run()

    gmx_energy=Load_energy(clean=False)
    gmx_forces=Load_forces(clean=False)
    print(gmx_energy)
    # Compare
    print("########################################")
    result_energy=Compare_energy(omm_energy[:,1:], gmx_energy[:,1:], isPrint=True)
    result_forces=Compare_forces(omm_forces[:,1:], gmx_forces[:,1:], isPrint=True)

    return result_energy and result_forces

In [26]:
Compare_OMM_GMX(working_dir)

/home/ys/CommonUse/Martini/CTGoMartini/tests/data/UmbrellaSampling
[[      0.         -238821.85051891]]
[[      0.       -238820.420921]]
########################################
Energy Compare
Absolute error: 1.42960
Relative error: 0.00001
Energies match!
###Forces Compare###
Max absolute error: 53.47141
Max relative error: 0.39745
      Max allclose: 53.45748
Error: Forces do not match!


False

In [32]:
Compare_OMM_GMX(working_dir)

/home/ys/CommonUse/Martini/CTGoMartini/tests/data/UmbrellaSampling/GlnBP/
[[      0.         -238820.42090518]]
[[      0.       -238820.420921]]
########################################
Energy Compare
Absolute error: 0.00002
Relative error: 0.00000
Energies match!
###Forces Compare###
Max absolute error: 0.00132
Max relative error: 0.00001
      Max allclose: -0.00001
Forces match!


/home/ys/CommonUse/Martini/CTGoMartini/tests/api/function.py:311: RuntimeWarning: invalid value encountered in divide
  relative_force_error = np.linalg.norm(forces1 - forces2, axis=1) / average


True

In [35]:
def Compare_OMM_GMX(working_dir, epsilon_r=15.0):
    print(working_dir)
    os.chdir('/home/ys/SongYang/MultipleBasin/Work/ContactOpt/GlnBP/MBContact8-Umbrella/Validation/repeat-open-gmx-300_-310_0/Run/window_18_bk_openmm')
    strfile = "md18.gro"
    topfile = "../../system.top"

    simulation = OMM_setSimulation(strfile, topfile, epsilon_r=epsilon_r, temperature=310.15, double_precision=True)
    OMM_calStrfile(strfile, simulation, set_vsite=True)

    omm_energy=Load_energy(clean=True)
    omm_forces=Load_forces(clean=True)
    print(omm_energy)
    # gmx
    os.chdir('/home/ys/SongYang/MultipleBasin/Work/ContactOpt/GlnBP/MBContact8-Umbrella/Validation/repeat-open-gmx-300_-310_0/Run/window_18_bk')

    # GMX_set(CreateMDP=False, double_precision=True)
    GMX_run()

    gmx_energy=Load_energy(clean=False)
    gmx_forces=Load_forces(clean=False)
    print(gmx_energy)
    # Compare
    print("########################################")
    result_energy=Compare_energy(omm_energy[:,1:], gmx_energy[:,1:], isPrint=True)
    result_forces=Compare_forces(omm_forces[:,1:], gmx_forces[:,1:], isPrint=True)

    return result_energy and result_forces

In [36]:
Compare_OMM_GMX('./', epsilon_r=15.0)

./
[[      0.         -631042.22491066]]
[[      0.       -631040.821861]]
########################################
Energy Compare
Absolute error: 1.40305
Relative error: 0.00000
Energies match!
###Forces Compare###
Max absolute error: 64.87774
Max relative error: 0.61456
      Max allclose: 64.86717
Error: Forces do not match!


False